server:
  port: 17777
  servlet:
    context-path: /scheduler
    encoding:
      force: true
      charset: UTF-8
  jetty:
    threadpool:
      min-threads: 8
      max-threads: 200
      idle-timeout: 60000
    connection-idle-timeout: 30000
    stop-timeout: 30000
    max-http-form-post-size: 200000
    max-http-header-size: 8192
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
    banner:
      charset: UTF-8
    application:
        name: quartz-api-scheduler
    freemarker:
        request-context-attribute: request
        suffix: .html
        content-type: text/html
        enabled: true
        cache: false
        charset: UTF-8
        allow-request-override: false
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        settings:
          number_format: 0.##
          default_encoding: UTF-8
#          template_loader: templates
#    mvc:
#      static-path-pattern: /statics/**
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/quartz
      username: postgres
      password: root123
      # hikari连接池配置
      hikari:
        #连接池名
        pool-name: HikariCP
        #最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 600000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 30000
        # 连接测试query
        connection-test-query: SELECT 1
    quartz:
      job-store-type: jdbc
      jdbc:
        initialize-schema: always
      properties:
        org.quartz.scheduler.instanceName: QuartzScheduler
        org.quartz.scheduler.instanceId: AUTO
        org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        org.quartz.jobStore.tablePrefix: QRTZ_
        org.quartz.jobStore.dataSource: dataSource   # 指向 Spring Boot 默认的 Hikari DataSource
#        org:
#          quartz:
#            dataSource:
#                quartz:
#                  connectionProvider:
#                    class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
#            jobStore:
#              dataSource: quartz
#              class: org.quartz.impl.jdbcjobstore.JobStoreTX
#              clusterCheckinInterval: 10000
#              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#              isClustered: true
#              tablePrefix: QRTZ_
#              useProperties: false
#            scheduler:
#              instanceId: AUTO
#              instanceName: clusteredScheduler
#            threadPool:
#              class: org.quartz.simpl.SimpleThreadPool
#              threadCount: 10
#              threadPriority: 5
#              threadsInheritContextClassLoaderOfInitializingThread: true